---

- name: install php 5
  apt: name={{ item }} state=latest
  with_items:
    - php5
    - php5-cgi
    - php5-cli
    - php5-curl
    - php5-json
    - php5-odbc
    - php5-tidy
    - php5-common
    - php5-sqlite
    - php5-xmlrpc
  notify: restart apache
